### PR TITLE
SMS Twilio Integration

### PR DESCRIPTION
**Pull request by halkeye**
Looks like you vendored the other libraries, so i just grabbed https://github.com/twilio/twilio-php/archive/master.zip and committed it.

Seems to work for me. Is there a standard way to report errors back? should I be using error_log maybe?

### CODE REVIEW

**Comment by coudot** [comment]
Hello @halkeye 

Thanks for the PR. But importing 1600+ files in the project is not a good idea, even if it is a vendor library. I don't want to extend the code base, we should find a way either to let users download the library, either to choose only the relevant files needed.

**Comment by halkeye** [comment]
@coudot thats a super super good point, and waking up this morning the answer seems obvious.

This is just a single api call, so i'm going to revert ea63cbb and just use curl (like the one mentioned in #331).

on #331 you mention the wiki page, would that be preferred? or is a simple script here fine.

**Comment by coudot** [comment]
I think we can do both: provide the sample script and a documentation on the wiki

**Comment by halkeye** [comment]
Okay, new version, handful of lines.

Added a bunch of notes as the comment on the top on what to setup/how to use

```php
/*
 * Add to your config.inc.local.php
 * Credentials are on the main page of the dashboard - https://www.twilio.com/console
 * Phone numbers can be purchased and managed from the phone number dashboard
 * - https://www.twilio.com/console/phone-numbers/search
 *
 * $twilio_sid = '<sid>';
 * $twilio_auth_token = '<authtoken>';
 * $twilio_outgoing_number = '+18881234567';
 * true if you want to ask twilio if the number is valid, and reformat it
 * false otherwise
 * $twilio_lookup_first = true / false
 */
```

**Comment by coudot** [comment]
Doc: https://ltb-project.org/documentation/self-service-password/1.4/sms_api#twilio

PR #333 merged

Thanks!

**Comment by halkeye** [comment]
Awesome.

You may want to add the other config values to the wiki as well

**Comment by coudot** [comment]
Done

**Pull request merged**
