### PR TITLE
SMS OVH provider

### PR DESCRIPTION
**Pull request by dgeo**
Added OVH's php-sms-api via composer
Switched ReCaptcha to use composer (simplifies vendor/autoload.php !)
Added an optional parameter to send_sms_by_api() to get provider's config

### CODE REVIEW

**Comment by dgeo** [comment]
I switched recaptcha to composer because composer use did break existing one (overriding autoload.php)
Nos sure if this is how you want to manage vendors/ dir ?

**Comment by dgeo** [comment]
well… I switched PHPMailer, ReCaptcha to composer too, with few changes on includes.
Tell me if you prefer a less-invasive change… (I tested recaptcha, phpmailer and - of course - OVH sms)
"vendor"'s code could also live alone (as git submodules or requiring "cd lib; composer install" after cloning)

**Comment by coudot** [comment]
Thanks a lot for this pull request but it is really huge, I need time to review it.

**Comment by coudot** [comment]
This PR is really too big, we need to split it. Introducing composer is quite a big change and requires a separate PR. This could be done after 1.4 release.

**Comment by dgeo** [comment]
now this is as light as it can be ;)

**Comment by coudot** [comment]
Including OVH API in composer is quite heavy, for a feature most user will not use. I'm not sure if we should have it by default.

**Comment by dgeo** [comment]
I think you are right… could this work if I create another "composer.json" in a subdir with sms script ?
I'd like to be able to deploy this without patching existing files

**Comment by dgeo** [comment]
(and I'm not a real dev… just hacking there)

**Comment by coudot** [comment]
Maybe this could be a separated project? I will think about it.

**Comment by dgeo** [comment]
now this can be taken apart. I didn't include vendor/, only composer.json and I completed the doc

**Comment by dgeo** [comment]
You prefer that I maintain this in a separate project ? so we could close this PR ?

**Comment by dgeo** [comment]
changes are still needed in htdocs/sendsms.php anyway…

**Comment by coudot** [comment]
Hello,

your current solution seems ok: let administrators run composer to install required dependencies.

I will include it like for 1.4 release.

**Pull request merged**
