### PR TITLE
Add Arabic language support in docs

### PR DESCRIPTION
**Pull request by toky0**

### CODE REVIEW

**Comment by coudot** [comment]
Hello, thanks for this proposition.

My question is about the flag, is it the correct one? I checked https://en.wikipedia.org/wiki/List_of_Arab_flags but did not found a common flag.

**Comment by toky0** [comment]
Hi, Thanks for the quick review.

You're right, there's no common flag. We generally use one with the four colors white, green, red, and black like UAE, PS, or JO. I picked PS here.

**Comment by coudot** [comment]
Could you rebase on master?

**Comment by coudot** [comment]
Rebase done in #989

**Pull request closed without merging**
