### PR TITLE
Using ldap_exop_passwd if available (PHP>=7.2)

### PR DESCRIPTION
**Pull request by MCMic**
Attempt at #155 
This is not tested.

### CODE REVIEW

**Comment by coudot** [comment]
Thanks but we need a more complex code: even if the function exists, we want to be able to use it per configuration settings, as we might have an LDAP server that does not support the exop.

Anyway, we can use your code as implementation example when we will work on the feature.

**Comment by dgeo** [comment]
Would you prefer a "exop" value for $hash (as using exop removes the need for hashing passwords) ?
I may PR this quickly…

**Comment by dgeo** [comment]
Another tentative implementation here: https://github.com/criecm/self-service-password/commit/bda96b1a917b4ab475f93ccc8317cfd9662ba707
The idea is tu use 'exop' as hash value to use it

**Comment by coudot** [comment]
My idea is to add an option to use the exop method, it is not linked to the hash method.

**Comment by dgeo** [comment]
it may be viewed as 'the server will hash it himself', we need to keep it clear until that ;)
I wrote this one quickly because I needed it…

**Pull request merged**
