### PR TITLE
Upgrade Bootstrap to 5.3

### LINKED ISSUE #834: Update bootstrap library
bootstrap library is quite old: 3.4.1
We should at least update to bootstrap 4, for having features linked to progressbar

### PR DESCRIPTION
**Pull request by coudot**
Fix #834

### CODE REVIEW

**Comment by coudot** [comment]
@davidcoutadeur you need to run `composer update` to get the new bootstrap version

**Comment by davidcoutadeur** [comment]
I have just removed bootstrap-theme.min.css inclusion, as it seems to have been removed in bootstrap 5.3

**Review by davidcoutadeur — COMMENTED** [review]
I have made some basics tests.
Seems all fine to me.

**Comment by coudot** [comment]
Perfect, thanks for the feedback

**Pull request merged**
