### PR TITLE
added support for pwned-passwords api v2

### PR DESCRIPTION
**Pull request by 413j0**
added support for using https://github.com/ron-maxweb/pwned-passwords to check if the password has been on a breach

### CODE REVIEW

**Comment by coudot** [comment]
Very nice!

We will review the code and see if can include it in 1.3 release

**Comment by coudot** [comment]
@413j0 could you fix the unit test so we can merge this pull request?

**Comment by 413j0** [comment]
@coudot now it is passing for PHP 7

**Comment by coudot** [comment]
@413j0 congratulations. I will merge your code and we will see how fix support for PHP < 7.

**Comment by coudot** [comment]
@plewin code is merged, you can work on it if you want.

**Pull request merged**
