### PR TITLE
Spec file clean up

### PR DESCRIPTION
**Pull request by xavierba**
Hi,

I had this taking dust on a shelf, I guess it's better to have this upstream rather than in a fork :-)

Regards,
Xavier

### CODE REVIEW

**Comment by coudot** [comment]
Hello,

thanks for this PR.

Some questions:
* Conf is moved to /etc/self-service-password, right? How will this work when updating the package?
* We advise to create a local configuration (config.inc.local.php), is this compatible with your packaging guidelines?

**Comment by coudot** [comment]
Hello @xavierba 

did you saw my previous questions?

There are a lot of changes in your PR and I fear that it will break updates.

**Comment by xavierba** [comment]
hi @coudot
Sorry for the very late answer.
I just rebased on top of master.

About the conf file, moving it from the older locations to the new one is taken care of in the %post section.
There's no problem with having a config.inc.local.php file as long as it is in the same directory as config.inc.php.
Probably the config.inc.local.php file should be moved at the same time as the main config.inc.php. I'll add another commit to do that.

**Comment by xavierba** [comment]
The idea is to possibly include it in Fedora/EPEL and maintain it there. Both spec can indeed be kept in sync.  At least, cleaning up the upstream spec cannot hurt.

**Comment by coudot** [comment]
My concern  is about users installing from our packages and knowing where the files are. It will impact all their documentations.

**Pull request closed without merging**
