### PR TITLE
Implements strong cryptography with defuse-crypto 2.0.3

### PR DESCRIPTION
**Pull request by plewin**
- Removes mcrypt and its mentions
- Uses random_int and random_bytes instead of mt_rand
- Update README
- Adds defuse-crypto + random_compat libraries

Uses defuse-crypto 2.0.3 (lib/defuse-crypto.phar), has random_compat embedded.

Solves :
https://github.com/ltb-project/self-service-password/issues/85 https://github.com/ltb-project/self-service-password/issues/60 https://github.com/ltb-project/self-service-password/issues/59

Impact for people already using SSP : reset tokens are now twice as large (75 -> 140 characters for me)

Impacts for new installations : mcrypt is no more required for encrypted tokens and sms feature.
Strong encryption functions are now required for random_compat (php 7 or libsodium or /dev/urandom readable or installing php-mcrypt)

### CODE REVIEW

**Comment by coudot** [comment]
Hi @plewin , thanks a lot for this work.
Some remarks before merging:
* defuse is a third part library, it would be better to have it in lib/vendor instead of lib/
* We should write a simple unit test that call encrypt/decrypt methods and verify that we got the expected result (which is a string encrypted then decrypted is the same than the original)

**Comment by plewin** [comment]
Hi @coudot, I updated the pull request with your remarks.

**Comment by plewin** [comment]
@coudot please do not merge it now, i found something I want to improve

**Comment by plewin** [comment]
I reproduced the old behavior, tempered encrypted tokens gives silent errors.
Initially in this pull request, exceptions were thrown. I prefer to no change the behavior in this PR.
This PR is ready for merge.

**Pull request merged**
